/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'David' at '11/1/16 12:47 PM' with Gradle 3.1
 *
 * @author David, @date 11/1/16 12:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
